### ISSUE TITLE
KerberosSupportedEncryptionType: New resource proposal

### ISSUE THREAD

**Issue by fullenw1** [dsccommunity/SChannelDsc#1]
### Description
Thanks for having created this very useful module.
I am already testing it...

Here is another possible related resource:
It's a GPO named: **Network Security: Configure encryption types allowed for Kerberos**

Documentation:

 - https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/network-security-configure-encryption-types-allowed-for-kerberos

- https://www.stigviewer.com/stig/windows_server_2008_r2_member_server/2016-12-19/finding/V-21954

### Proposed properties
SupportedEncryptionTypes:

- DES_CBC_CRC: Enabled|Disabled
- DES_CBC_MD5: Enabled|Disabled
- RC4_HMAC_MD5: Enabled|Disabled
- AES128_HMAC_SHA1: Enabled|Disabled
- AES256_HMAC_SHA1: Enabled|Disabled
- Future encryption types: Enabled|Disabled

**Comment by ykuijs** [comment]
Am working on implementing this functionality. Will be included in next version.
