### ISSUE TITLE
Update Documentation: Add WinHttpDefaultSecureProtocols to SChannelSettingWiki

### ISSUE THREAD

**Issue by aydeisen** [dsccommunity/SChannelDsc#10]
[SChannelSettings.zip](https://github.com/dsccommunity/SChannelDsc/files/5074864/SChannelSettings.zip)

Update the wiki to include the `WinHttpDefaultSecureProtocols` parameter to the SChannelSettings documentation

NOTE: I've done the edit, but there's no way to fork a Wiki and do a pull request.  The edit is attached, with the following changes made

- Add WinHttpDefaultSecureProtocols to table
- Sort non-key parameters in alpha order
- Remove multiple blanks (MD012/no -multiple-blanks)

**Comment by ykuijs** [comment]
Thanks for letting me know! Will update the Wiki asap!

**Comment by ykuijs** [comment]
Updated!
