### ISSUE TITLE
SChannelDsc resource published on PowerShell Gallery is out of date

### ISSUE THREAD

**Issue by jachin84** [dsccommunity/SChannelDsc#14]
The version of this module is currently at 1.2.1 however the PowerShell Gallery version is 1.2.0. Any chance we can get the newer version published?

**Comment by johlju** [comment]
A preview version has been published now - there was an issue with the pipeline that seems to have been sorted. @ykuijs do you want to push a full release so we can make sure it releases as expected?

**Comment by ykuijs** [comment]
v1.2.2 has been released to the PowerShell Gallery
